// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3sy9-Kz8uiFUzjmnMa_tl3hhQt2pNOfQ',
    appId: '1:456271247026:web:20ce064814f6264132bbab',
    messagingSenderId: '456271247026',
    projectId: 'wash-app-70eaa',
    authDomain: 'wash-app-70eaa.firebaseapp.com',
    storageBucket: 'wash-app-70eaa.firebasestorage.app',
    measurementId: 'G-LXK34HTTGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVA1XDaJ-uVXh_Ahm48iFOcl-xgxy9x3Y',
    appId: '1:456271247026:android:eef132b81486027d32bbab',
    messagingSenderId: '456271247026',
    projectId: 'wash-app-70eaa',
    storageBucket: 'wash-app-70eaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAoT6xRGZbIqCXgpsDel0rHj_KvQH0eCc',
    appId: '1:456271247026:ios:a1e8786a2bcc7c5332bbab',
    messagingSenderId: '456271247026',
    projectId: 'wash-app-70eaa',
    storageBucket: 'wash-app-70eaa.firebasestorage.app',
    iosClientId: '456271247026-0k63cehs1e3vc08gqj24h8pn7q5pns4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.washBeshr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAoT6xRGZbIqCXgpsDel0rHj_KvQH0eCc',
    appId: '1:456271247026:ios:a1e8786a2bcc7c5332bbab',
    messagingSenderId: '456271247026',
    projectId: 'wash-app-70eaa',
    storageBucket: 'wash-app-70eaa.firebasestorage.app',
    iosClientId: '456271247026-0k63cehs1e3vc08gqj24h8pn7q5pns4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.washBeshr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3sy9-Kz8uiFUzjmnMa_tl3hhQt2pNOfQ',
    appId: '1:456271247026:web:90ad7249be7775cb32bbab',
    messagingSenderId: '456271247026',
    projectId: 'wash-app-70eaa',
    authDomain: 'wash-app-70eaa.firebaseapp.com',
    storageBucket: 'wash-app-70eaa.firebasestorage.app',
    measurementId: 'G-N5BLQ5NG88',
  );
}
